>set(CMAKE_BUILD_TYPE Release)

set(ENABLE_BUNDLED_ZLOG ON)
set(ENABLE_BUNDLED_P4EST ON)
set(ENABLE_BUNDLED_ZLIB ON)

set(ENABLE_BUNDLED_HDF5 ON)

set(USE_TCMALLOC ON)
set(ENABLE_BUNDLED_TCMALLOC ON)

#for intel
set(BLA_VENDOR Intel10_64lp_seq)
set(ENABLE_BUNDLED_BLAS OFF)
set(PETSC_PREFIX "/scinet/niagara/software/2018a/opt/intel-2018.2-intelmpi-2018.2/petsc/3.9.2/")
