set(CMAKE_BUILD_TYPE Release)

set(ENABLE_BUNDLED_ZLOG ON)
set(ENABLE_BUNDLED_P4EST ON)
set(ENABLE_BUNDLED_PETSC ON)
set(ENABLE_BUNDLED_ZLIB ON)
set(ENABLE_BUNDLED_BLAS ON)
set(ENABLE_BUNDLED_HDF5 ON)

set(USE_TCMALLOC ON)
set(ENABLE_BUNDLED_TCMALLOC ON)

