name: Testing (Linux)
on:
  push:
    branches:
      - master
  pull_request:

env:
  GCC_VERSION: 10
  OMP_NUM_THREADS: "2"

jobs:
  cpptests_debug:
    name: C Debug tests (Linux)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:    
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # for codecov

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y -q install cmake gcc-10 g++-10 mpich

      - name: Build 
        run: |
            ln -s ./support/Machines/Bundled/bundled_Debug.cmake ./cmake/machine.cmake
            cmake . -BBuild ../ -DCMAKE_BUILD_TYPE=Debug
            cmake --build ./Build

      - name: Build and run unit tests for code Coverage
        run: |
            cd Build && ctest -V    
  cpptests_release:
    name: C Release tests (Linux)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # for codecov

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y -q install cmake gcc-10 g++-10 mpich
        
      - name: Build 
        run: |
            ln -s ./support/Machines/Bundled/bundled_Release.cmake ./cmake/machine.cmake
            cmake . -BBuild ../ -DCMAKE_BUILD_TYPE=Release
            cmake --build ./Build

      - name: Build and run unit tests for code Coverage
        run: |
            cd Build && ctest -V    
